name: Build and Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

#      - name: Run docker-compose
#        uses: hoverkraft-tech/compose-action@v2.0.1

      - name: Run docker compose
        uses: docker compose --build -d

      - name: Wait for Server to be Ready
        run: |
          echo "Waiting for server..."
          sleep 10

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Install Playwright browser
        run: bunx playwright install chromium

      - name: debug
        run: docker ps -a

      - name: Run tests
        run: bun run test

      - name: Shutdown docker container
        run: docker compose down
